"""initial_schema

Revision ID: 780489bdb99d
Revises: 
Create Date: 2026-05-03 14:36:31.274517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780489bdb99d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translation_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('translation_json')

    # ### end Alembic commands ###
